import { BriefcaseBusiness, ChevronDown, Plus, Quote, Trash2, X } from "lucide-react";
import { useState } from "react";
import type { ContentBundle, PracticeCase } from "../../types";
import { uniqueId } from "../studioHelpers";

interface Props { bundle: ContentBundle; onChange: (next: ContentBundle | ((current: ContentBundle) => ContentBundle)) => void; }

export function CaseStudyEditor({ bundle, onChange }: Props) {
  const [caseIndex, setCaseIndex] = useState(0);
  const practiceCase = bundle.practiceCases[caseIndex];
  const update = (fn: (draft: PracticeCase) => void) => onChange((draft) => { const target = draft.practiceCases[caseIndex]; if (target) fn(target); return draft; });
  if (!practiceCase) return <section><div className="studio-page-heading"><span className="studio-kicker">Pearson Business</span><h1>Extended-writing case studies</h1></div><div className="studio-empty"><BriefcaseBusiness /><h2>No practice cases found</h2></div></section>;
  return <section><div className="studio-page-heading"><span className="studio-kicker">Pearson Business only</span><h1>Edit extended-writing case studies carefully</h1><p>These fictional sources should keep the length, tone and evidence density of Pearson material. Edit the source, figures, questions and model strands together so every answer still uses the case.</p></div><div className="studio-case-picker"><label><span>Choose a case study</span><select value={caseIndex} onChange={(event) => setCaseIndex(Number(event.target.value))}>{bundle.practiceCases.map((item, index) => <option key={item.id} value={index}>{item.title}</option>)}</select></label><span>Stable case ID: {practiceCase.id}</span></div><div className="studio-editor-stack">
    <details className="studio-card studio-question-card" open><summary><span><BriefcaseBusiness />Case title and source</span><ChevronDown /></summary><div className="studio-card-body studio-form-grid"><label><span>Business name</span><input value={practiceCase.title} onChange={(event) => update((draft) => { draft.title = event.target.value; })} /></label><label><span>Theme label</span><input value={practiceCase.theme} onChange={(event) => update((draft) => { draft.theme = event.target.value; })} /></label><label><span>Source section</span><select value={practiceCase.sourceSection} onChange={(event) => update((draft) => { draft.sourceSection = event.target.value as PracticeCase["sourceSection"]; })}><option>Section B</option><option>Section C</option></select></label><label className="wide"><span>Student instruction</span><textarea rows={2} value={practiceCase.sourceInstruction} onChange={(event) => update((draft) => { draft.sourceInstruction = event.target.value; })} /></label></div></details>
    <details className="studio-card studio-question-card" open><summary><span><Quote />Case-study paragraphs</span><ChevronDown /></summary><div className="studio-card-body"><p className="studio-editor-help">Keep facts, numbers, decisions and uncertainty spread across several paragraphs. Students need evidence they can select and connect.</p><div className="studio-repeat-list">{practiceCase.context.map((paragraph, index) => <div className="studio-repeat-row" key={index}><textarea rows={5} value={paragraph} onChange={(event) => update((draft) => { draft.context[index] = event.target.value; })} /><button type="button" onClick={() => update((draft) => { draft.context.splice(index, 1); })}><X /></button></div>)}<button className="studio-primary-button" type="button" onClick={() => update((draft) => { draft.context.push(""); })}><Plus /> Add source paragraph</button></div></div></details>
    <details className="studio-card studio-question-card"><summary><span><Quote />Evidence students should notice</span><ChevronDown /></summary><div className="studio-card-body"><div className="studio-section-toolbar"><p>These hooks help the website teach case-study application.</p><button className="studio-primary-button" type="button" onClick={() => update((draft) => { draft.evidence.push({ id: uniqueId("evidence", practiceCase.id), label: "New evidence", quote: "Exact fact or number", meaning: "Explain why this matters." }); })}><Plus /> Add evidence</button></div>{practiceCase.evidence.map((evidence, index) => <div className="studio-list-card studio-evidence-row" key={evidence.id}><label><span>Label</span><input value={evidence.label} onChange={(event) => update((draft) => { draft.evidence[index].label = event.target.value; })} /></label><label><span>Exact case fact</span><input value={evidence.quote} onChange={(event) => update((draft) => { draft.evidence[index].quote = event.target.value; })} /></label><label className="grow"><span>What it can show</span><textarea rows={2} value={evidence.meaning} onChange={(event) => update((draft) => { draft.evidence[index].meaning = event.target.value; })} /></label><button type="button" onClick={() => update((draft) => { draft.evidence.splice(index, 1); })}><Trash2 /></button></div>)}</div></details>
    <details className="studio-card studio-question-card"><summary><span><BriefcaseBusiness />Figure and chart</span><ChevronDown /></summary><div className="studio-card-body studio-form-grid"><label className="wide"><span>Chart title</span><input value={practiceCase.chartTitle} onChange={(event) => update((draft) => { draft.chartTitle = event.target.value; })} /></label>{practiceCase.chart.map((bar, index) => <div className="studio-case-chart-row" key={index}><input value={bar.label} onChange={(event) => update((draft) => { draft.chart[index].label = event.target.value; })} /><input type="number" value={bar.value} onChange={(event) => update((draft) => { draft.chart[index].value = Number(event.target.value); })} /><input value={bar.display} onChange={(event) => update((draft) => { draft.chart[index].display = event.target.value; })} /></div>)}<label><span>Supporting figure title</span><input value={practiceCase.supportingFigure.title} onChange={(event) => update((draft) => { draft.supportingFigure.title = event.target.value; })} /></label><label className="wide"><span>Supporting figure text</span><textarea rows={3} value={practiceCase.supportingFigure.body ?? ""} onChange={(event) => update((draft) => { draft.supportingFigure.body = event.target.value; })} /></label></div></details>
    <details className="studio-card studio-question-card"><summary><span><BriefcaseBusiness />Main extended question</span><ChevronDown /></summary><div className="studio-card-body studio-form-grid"><label><span>Command word</span><select value={practiceCase.question.command} onChange={(event) => update((draft) => { draft.question.command = event.target.value as PracticeCase["question"]["command"]; })}><option>Analyse</option><option>Justify</option><option>Evaluate</option></select></label><label><span>Marks</span><input type="number" min={1} max={12} value={practiceCase.question.marks} onChange={(event) => update((draft) => { draft.question.marks = Number(event.target.value); })} /></label><label className="wide"><span>Question wording</span><textarea rows={3} value={practiceCase.question.prompt} onChange={(event) => update((draft) => { draft.question.prompt = event.target.value; })} /></label></div></details>
    <details className="studio-card studio-question-card"><summary><span><BriefcaseBusiness />Connected answer strands</span><ChevronDown /></summary><div className="studio-card-body"><div className="studio-repeat-list">{practiceCase.strands.map((strand, index) => <div className="studio-case-strand" key={index}><input value={strand.label} onChange={(event) => update((draft) => { draft.strands[index].label = event.target.value; })} /><textarea rows={3} value={strand.text} onChange={(event) => update((draft) => { draft.strands[index].text = event.target.value; })} /><button type="button" onClick={() => update((draft) => { draft.strands.splice(index, 1); })}><Trash2 /></button></div>)}<button className="studio-primary-button" type="button" onClick={() => update((draft) => { draft.strands.push({ label: "Leads to", text: "Connect the case evidence to a consequence." }); })}><Plus /> Add strand</button></div><div className="studio-field-heading studio-model-heading"><span>Model answer paragraphs</span><button type="button" onClick={() => update((draft) => { draft.model.push(""); })}><Plus /> Add paragraph</button></div>{practiceCase.model.map((paragraph, index) => <div className="studio-repeat-row" key={index}><textarea rows={4} value={paragraph} onChange={(event) => update((draft) => { draft.model[index] = event.target.value; })} /><button type="button" onClick={() => update((draft) => { draft.model.splice(index, 1); })}><X /></button></div>)}</div></details>
  </div></section>;
}
