import { ChevronDown, Copy, Eye, FilePlus2, GripVertical, ImagePlus, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import type { ContentBundle, CustomPage, EditableTopicSection } from "../../types";
import { createCustomPage, createSection, listToLines, linesToList, prepareImage, uniqueId, type PendingAsset } from "../studioHelpers";

interface Props { bundle: ContentBundle; onChange: (next: ContentBundle | ((current: ContentBundle) => ContentBundle)) => void; assets: PendingAsset[]; onAssetsChange: (assets: PendingAsset[]) => void; }

export function PageEditor({ bundle, onChange, assets, onAssetsChange }: Props) {
  const [pageIndex, setPageIndex] = useState(0);
  const [preview, setPreview] = useState(false);
  const page = bundle.customPages[pageIndex];
  const updatePage = (fn: (page: CustomPage) => void) => onChange((draft) => { const target = draft.customPages[pageIndex]; if (target) fn(target); return draft; });
  const addPage = () => { onChange((draft) => { draft.customPages.push(createCustomPage()); return draft; }); setPageIndex(bundle.customPages.length); };
  return <section><div className="studio-page-heading"><span className="studio-kicker">Extra pages</span><h1>Create a page from simple building blocks</h1><p>Use this for study guidance, department news or a new resource page. It will use the existing site look automatically.</p></div>
    <div className="studio-page-picker"><label><span>Choose a page</span><select value={pageIndex} disabled={!bundle.customPages.length} onChange={(event) => setPageIndex(Number(event.target.value))}>{bundle.customPages.map((item, index) => <option key={item.id} value={index}>{item.title}</option>)}</select></label><button className="studio-primary-button" type="button" onClick={addPage}><FilePlus2 /> Create page</button></div>
    {!page ? <div className="studio-empty"><FilePlus2 /><h2>No extra pages yet</h2><p>The main qualification pages are already safe. Create an extra page only when you need one.</p><button className="studio-primary-button" type="button" onClick={addPage}><Plus /> Create the first page</button></div> : <>
      <nav className="studio-tabs"><button className={!preview ? "active" : ""} type="button" onClick={() => setPreview(false)}><FilePlus2 /> Edit page</button><button className={preview ? "active" : ""} type="button" onClick={() => setPreview(true)}><Eye /> Preview</button></nav>
      {!preview ? <div className="studio-editor-stack"><div className="studio-card studio-card-body studio-form-grid"><label className="wide"><span>Page title</span><input value={page.title} onChange={(event) => updatePage((draft) => { draft.title = event.target.value; })} /></label><label className="wide"><span>Short introduction</span><textarea rows={3} value={page.summary ?? ""} onChange={(event) => updatePage((draft) => { draft.summary = event.target.value; })} /></label><label><span>Page address</span><div className="studio-prefix-input"><span>/page/</span><input value={page.slug} onChange={(event) => updatePage((draft) => { draft.slug = event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-"); })} /></div><small>Changing this later will change the web link.</small></label><label className="studio-checkbox"><input type="checkbox" checked={page.showInNavigation} onChange={(event) => updatePage((draft) => { draft.showInNavigation = event.target.checked; })} /><span>Show this page in the main menu</span></label></div><div className="studio-section-toolbar"><div><h2>Page sections</h2><p>Move sections with the handles and arrows, then open one to edit it.</p></div><button className="studio-primary-button" type="button" onClick={() => updatePage((draft) => { draft.sections.push(createSection()); })}><Plus /> Add section</button></div>{page.sections.map((section, index) => <PageSectionEditor key={(section as EditableTopicSection).id ?? index} section={section as EditableTopicSection} index={index} assets={assets} onAssetsChange={onAssetsChange} onChange={(next) => updatePage((draft) => { draft.sections[index] = next; })} onDuplicate={() => updatePage((draft) => { const copy = structuredClone(section) as EditableTopicSection; copy.id = uniqueId("page-section", copy.heading); copy.heading += " (copy)"; draft.sections.splice(index + 1, 0, copy); })} onDelete={() => updatePage((draft) => { draft.sections.splice(index, 1); })} />)}</div> : <div className="studio-preview"><div className="studio-preview-toolbar"><span><Eye /> Student preview</span></div><article className="studio-student-page"><span className="eyebrow">MEA Business and Technology Hub</span><h1>{page.title}</h1><p className="studio-preview-summary">{page.summary}</p>{page.sections.map((section, index) => { const asset = assets.find((item) => item.publicPath === section.image?.src); return <section key={index}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((bullet, bulletIndex) => <li key={bulletIndex}>{bullet}</li>)}</ul>}{section.image && <figure className="topic-illustration"><img src={asset?.previewUrl ?? `${import.meta.env.BASE_URL}${section.image.src}`} alt={section.image.alt} /><figcaption>{section.image.caption}</figcaption></figure>}</section>; })}</article></div>}
      <button className="studio-danger-button studio-remove-page" type="button" onClick={() => { if (window.confirm(`Remove the page “${page.title}”? You can use Undo afterwards.`)) { onChange((draft) => { draft.customPages.splice(pageIndex, 1); return draft; }); setPageIndex(0); } }}><Trash2 /> Remove this page</button>
    </>}
  </section>;
}

function PageSectionEditor({ section, index, assets, onAssetsChange, onChange, onDuplicate, onDelete }: { section: EditableTopicSection; index: number; assets: PendingAsset[]; onAssetsChange: (assets: PendingAsset[]) => void; onChange: (next: EditableTopicSection) => void; onDuplicate: () => void; onDelete: () => void }) {
  const [open, setOpen] = useState(index === 0);
  const update = (fn: (draft: EditableTopicSection) => void) => { const draft = structuredClone(section); fn(draft); onChange(draft); };
  const asset = assets.find((item) => item.publicPath === section.image?.src);
  const addImage = async (file?: File) => { if (!file) return; try { const prepared = await prepareImage(file); onAssetsChange([...assets, prepared]); update((draft) => { draft.image = { src: prepared.publicPath, alt: "", caption: "" }; }); } catch (caught) { window.alert(caught instanceof Error ? caught.message : "The image could not be added."); } };
  return <article className={`studio-section-card${open ? " open" : ""}`}><header><span className="studio-drag-handle"><GripVertical /></span><button className="studio-section-title" type="button" onClick={() => setOpen((value) => !value)}><span><small>Section {index + 1}</small><strong>{section.heading}</strong></span><ChevronDown /></button><div className="studio-row-actions"><button type="button" onClick={onDuplicate}><Copy /></button><button type="button" onClick={onDelete}><Trash2 /></button></div></header>{open && <div className="studio-section-body"><label><span>Heading</span><input value={section.heading} onChange={(event) => update((draft) => { draft.heading = event.target.value; })} /></label><div className="studio-repeat-list"><div className="studio-field-heading"><span>Paragraphs</span><button type="button" onClick={() => update((draft) => { draft.paragraphs.push(""); })}><Plus /> Add paragraph</button></div>{section.paragraphs.map((paragraph, paragraphIndex) => <div className="studio-repeat-row" key={paragraphIndex}><textarea rows={3} value={paragraph} onChange={(event) => update((draft) => { draft.paragraphs[paragraphIndex] = event.target.value; })} /><button type="button" onClick={() => update((draft) => { draft.paragraphs.splice(paragraphIndex, 1); })}><X /></button></div>)}</div><label><span>Bullet points <small>one per line</small></span><textarea rows={4} value={listToLines(section.bullets)} onChange={(event) => update((draft) => { draft.bullets = linesToList(event.target.value); })} /></label>{section.image ? <div className="studio-image-grid"><img src={asset?.previewUrl ?? `${import.meta.env.BASE_URL}${section.image.src}`} alt="Preview" /><div><label><span>Alternative text <b>required</b></span><textarea rows={3} value={section.image.alt} onChange={(event) => update((draft) => { if (draft.image) draft.image.alt = event.target.value; })} /></label><label><span>Caption</span><input value={section.image.caption} onChange={(event) => update((draft) => { if (draft.image) draft.image.caption = event.target.value; })} /></label><button type="button" onClick={() => update((draft) => { delete draft.image; })}><Trash2 /> Remove image</button></div></div> : <label className="studio-dropzone"><ImagePlus /><strong>Add an image</strong><span>Click to choose a file.</span><input type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={(event) => void addImage(event.target.files?.[0])} /></label>}</div>}</article>;
}
