import { ExternalLink, FolderKanban, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import type { ContentBundle, CourseId, ResourceLink } from "../../types";
import { uniqueId } from "../studioHelpers";

interface Props { bundle: ContentBundle; onChange: (next: ContentBundle | ((current: ContentBundle) => ContentBundle)) => void; }
const resourceTypes: ResourceLink["type"][] = ["Specification", "Past paper", "Mark scheme", "Examiner report", "Assessment guide", "Sample assignment", "Video", "External revision"];

export function ResourceEditor({ bundle, onChange }: Props) {
  const [courseId, setCourseId] = useState<CourseId>(bundle.courses[0]?.id ?? "business");
  const course = bundle.courses.find((item) => item.id === courseId);
  const resources = bundle.resources.map((item, index) => ({ item, index })).filter(({ item }) => item.courseId === courseId);
  const update = (index: number, fn: (resource: ResourceLink) => void) => onChange((draft) => { fn(draft.resources[index]); return draft; });
  const add = () => onChange((draft) => { draft.resources.push({ id: uniqueId("resource", courseId), courseId, title: "New learning resource", description: "Explain how this will help students.", type: "External revision", href: "https://", official: false }); return draft; });
  return <section><div className="studio-page-heading"><span className="studio-kicker">Materials</span><h1>Keep useful links clear and trustworthy</h1><p>Materials are always separated by qualification. Add the full secure web address, then use Open link to check it before publishing.</p></div>
    <div className="studio-course-tabs">{bundle.courses.map((item) => <button type="button" key={item.id} className={item.id === courseId ? "active" : ""} onClick={() => setCourseId(item.id)}>{item.shortTitle}<span>{bundle.resources.filter((resource) => resource.courseId === item.id).length}</span></button>)}</div>
    <div className="studio-section-toolbar"><div><h2>{course?.shortTitle} materials</h2><p>Official items receive a clear badge on the student site.</p></div><button className="studio-primary-button" type="button" onClick={add}><Plus /> Add material</button></div>
    <div className="studio-resource-list">{resources.map(({ item, index }) => <article className="studio-card studio-resource-editor" key={item.id}><div className="studio-resource-editor__header"><FolderKanban /><div><span>{item.type}</span><h3>{item.title}</h3></div>{item.official && <b><ShieldCheck /> Official</b>}</div><div className="studio-card-body studio-form-grid"><label className="wide"><span>Title shown to students</span><input value={item.title} onChange={(event) => update(index, (resource) => { resource.title = event.target.value; })} /></label><label><span>Type</span><select value={item.type} onChange={(event) => update(index, (resource) => { resource.type = event.target.value as ResourceLink["type"]; })}>{resourceTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="studio-checkbox"><input type="checkbox" checked={item.official} onChange={(event) => update(index, (resource) => { resource.official = event.target.checked; })} /><span>This comes from the exam board or school</span></label><label className="wide"><span>Helpful description</span><textarea rows={2} value={item.description} onChange={(event) => update(index, (resource) => { resource.description = event.target.value; })} /></label><label className="wide"><span>Full link</span><div className="studio-link-field"><input value={item.href} onChange={(event) => update(index, (resource) => { resource.href = event.target.value; resource.local = event.target.value.startsWith(import.meta.env.BASE_URL); })} /><a href={item.href} target="_blank" rel="noreferrer"><ExternalLink /> Open link</a></div><small>Use an address beginning with https://. Existing MEA documents may use the site address already shown.</small></label><button className="studio-danger-button" type="button" onClick={() => { if (window.confirm(`Remove “${item.title}”? You can use Undo afterwards.`)) onChange((draft) => { draft.resources.splice(index, 1); return draft; }); }}><Trash2 /> Remove material</button></div></article>)}</div>
  </section>;
}
